In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("C:/Users/Admin/Desktop/Brainybeam/Pumpkin_Seeds_Dataset.csv")
data

Area  Perimeter  Major_Axis_Length  Minor_Axis_Length  Convex_Area  \
0     56276    888.242           326.1485           220.2388        56831   
1     76631   1068.146           417.1932           234.2289        77280   
2     71623   1082.987           435.8328           211.0457        72663   
3     66458    992.051           381.5638           222.5322        67118   
4     66107    998.146           383.8883           220.4545        67117   
...     ...        ...                ...                ...          ...   
2495  79637   1224.710           533.1513           190.4367        80381   
2496  69647   1084.318           462.9416           191.8210        70216   
2497  87994   1210.314           507.2200           222.1872        88702   
2498  80011   1182.947           501.9065           204.7531        80902   
2499  84934   1159.933           462.8951           234.5597        85781   

      Equiv_Diameter  Eccentricity  Solidity  Extent  Roundness  \
0           267.6805        0.7376    0.9902  0.7453     0.8963   
1           312.3614        0.8275    0.9916  0.7151     0.8440   
2           301.9822        0.8749    0.9857  0.7400     0.7674   
3           290.8899        0.8123    0.9902  0.7396     0.8486   
4           290.1207        0.8187    0.9850  0.6752     0.8338   
...              ...           ...       ...     ...        ...   
2495        318.4289        0.9340    0.9907  0.4888     0.6672   
2496        297.7874        0.9101    0.9919  0.6002     0.7444   
2497        334.7199        0.8990    0.9920  0.7643     0.7549   
2498        319.1758        0.9130    0.9890  0.7374     0.7185   
2499        328.8485        0.8621    0.9901  0.7360     0.7933   

      Aspect_Ration  Compactness          Class  
0            1.4809       0.8207     Çerçevelik  
1            1.7811       0.7487     Çerçevelik  
2            2.0651       0.6929     Çerçevelik  
3            1.7146       0.7624     Çerçevelik  
4            1.7413       0.7557     Çerçevelik  
...             ...          ...            ...  
2495         2.7996       0.5973  Ürgüp Sivrisi  
2496         2.4134       0.6433  Ürgüp Sivrisi  
2497         2.2828       0.6599  Ürgüp Sivrisi  
2498         2.4513       0.6359  Ürgüp Sivrisi  
2499         1.9735       0.7104  Ürgüp Sivrisi  

[2500 rows x 13 columns]

In [3]:
data.head()

Area  Perimeter  Major_Axis_Length  Minor_Axis_Length  Convex_Area  \
0  56276    888.242           326.1485           220.2388        56831   
1  76631   1068.146           417.1932           234.2289        77280   
2  71623   1082.987           435.8328           211.0457        72663   
3  66458    992.051           381.5638           222.5322        67118   
4  66107    998.146           383.8883           220.4545        67117   

   Equiv_Diameter  Eccentricity  Solidity  Extent  Roundness  Aspect_Ration  \
0        267.6805        0.7376    0.9902  0.7453     0.8963         1.4809   
1        312.3614        0.8275    0.9916  0.7151     0.8440         1.7811   
2        301.9822        0.8749    0.9857  0.7400     0.7674         2.0651   
3        290.8899        0.8123    0.9902  0.7396     0.8486         1.7146   
4        290.1207        0.8187    0.9850  0.6752     0.8338         1.7413   

   Compactness       Class  
0       0.8207  Çerçevelik  
1       0.7487  Çerçevelik  
2       0.6929  Çerçevelik  
3       0.7624  Çerçevelik  
4       0.7557  Çerçevelik

In [4]:
data.tail()

Area  Perimeter  Major_Axis_Length  Minor_Axis_Length  Convex_Area  \
2495  79637   1224.710           533.1513           190.4367        80381   
2496  69647   1084.318           462.9416           191.8210        70216   
2497  87994   1210.314           507.2200           222.1872        88702   
2498  80011   1182.947           501.9065           204.7531        80902   
2499  84934   1159.933           462.8951           234.5597        85781   

      Equiv_Diameter  Eccentricity  Solidity  Extent  Roundness  \
2495        318.4289        0.9340    0.9907  0.4888     0.6672   
2496        297.7874        0.9101    0.9919  0.6002     0.7444   
2497        334.7199        0.8990    0.9920  0.7643     0.7549   
2498        319.1758        0.9130    0.9890  0.7374     0.7185   
2499        328.8485        0.8621    0.9901  0.7360     0.7933   

      Aspect_Ration  Compactness          Class  
2495         2.7996       0.5973  Ürgüp Sivrisi  
2496         2.4134       0.6433  Ürgüp Sivrisi  
2497         2.2828       0.6599  Ürgüp Sivrisi  
2498         2.4513       0.6359  Ürgüp Sivrisi  
2499         1.9735       0.7104  Ürgüp Sivrisi

In [5]:
data.describe()

Area    Perimeter  Major_Axis_Length  Minor_Axis_Length  \
count    2500.000000  2500.000000        2500.000000        2500.000000   
mean    80658.220800  1130.279015         456.601840         225.794921   
std     13664.510228   109.256418          56.235704          23.297245   
min     47939.000000   868.485000         320.844600         152.171800   
25%     70765.000000  1048.829750         414.957850         211.245925   
50%     79076.000000  1123.672000         449.496600         224.703100   
75%     89757.500000  1203.340500         492.737650         240.672875   
max    136574.000000  1559.450000         661.911300         305.818000   

         Convex_Area  Equiv_Diameter  Eccentricity     Solidity       Extent  \
count    2500.000000     2500.000000   2500.000000  2500.000000  2500.000000   
mean    81508.084400      319.334230      0.860879     0.989492     0.693205   
std     13764.092788       26.891920      0.045167     0.003494     0.060914   
min     48366.000000      247.058400      0.492100     0.918600     0.468000   
25%     71512.000000      300.167975      0.831700     0.988300     0.658900   
50%     79872.000000      317.305350      0.863700     0.990300     0.713050   
75%     90797.750000      338.057375      0.897025     0.991500     0.740225   
max    138384.000000      417.002900      0.948100     0.994400     0.829600   

         Roundness  Aspect_Ration  Compactness  
count  2500.000000    2500.000000  2500.000000  
mean      0.791533       2.041702     0.704121  
std       0.055924       0.315997     0.053067  
min       0.554600       1.148700     0.560800  
25%       0.751900       1.801050     0.663475  
50%       0.797750       1.984200     0.707700  
75%       0.834325       2.262075     0.743500  
max       0.939600       3.144400     0.904900

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Area               2500 non-null   int64  
 1   Perimeter          2500 non-null   float64
 2   Major_Axis_Length  2500 non-null   float64
 3   Minor_Axis_Length  2500 non-null   float64
 4   Convex_Area        2500 non-null   int64  
 5   Equiv_Diameter     2500 non-null   float64
 6   Eccentricity       2500 non-null   float64
 7   Solidity           2500 non-null   float64
 8   Extent             2500 non-null   float64
 9   Roundness          2500 non-null   float64
 10  Aspect_Ration      2500 non-null   float64
 11  Compactness        2500 non-null   float64
 12  Class              2500 non-null   object 
dtypes: float64(10), int64(2), object(1)
memory usage: 254.0+ KB


In [7]:
data.isnull().sum()

Area                 0
Perimeter            0
Major_Axis_Length    0
Minor_Axis_Length    0
Convex_Area          0
Equiv_Diameter       0
Eccentricity         0
Solidity             0
Extent               0
Roundness            0
Aspect_Ration        0
Compactness          0
Class                0
dtype: int64

In [33]:
from sklearn.preprocessing import LabelEncoder

In [34]:
x = data.iloc[:,0:4].values
print(x)

[[56276.       888.242    326.1485   220.2388]
 [76631.      1068.146    417.1932   234.2289]
 [71623.      1082.987    435.8328   211.0457]
 ...
 [87994.      1210.314    507.22     222.1872]
 [80011.      1182.947    501.9065   204.7531]
 [84934.      1159.933    462.8951   234.5597]]


In [35]:
y = data.iloc[:,12].values
print(y)

['Çerçevelik' 'Çerçevelik' 'Çerçevelik' ... 'Ürgüp Sivrisi'
 'Ürgüp Sivrisi' 'Ürgüp Sivrisi']


In [36]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=108)


In [37]:
x_train

array([[78423.    ,  1100.135 ,   441.6902,   227.0228],
       [68778.    ,  1025.168 ,   408.2745,   215.9211],
       [61949.    ,  1033.415 ,   439.7728,   179.6936],
       ...,
       [71410.    ,  1051.05  ,   418.8909,   218.0973],
       [70175.    ,  1029.917 ,   390.8671,   229.4874],
       [85039.    ,  1130.265 ,   433.7324,   250.862 ]])

In [38]:
y_train

array(['Çerçevelik', 'Ürgüp Sivrisi', 'Ürgüp Sivrisi', ...,
       'Ürgüp Sivrisi', 'Çerçevelik', 'Çerçevelik'], dtype=object)

In [40]:
x_test

array([[50822.    ,   917.53  ,   381.4619,   170.2289],
       [67164.    ,  1004.562 ,   396.569 ,   217.0065],
       [95832.    ,  1229.239 ,   501.0219,   244.0251],
       ...,
       [65593.    ,   975.947 ,   376.7856,   222.4426],
       [81401.    ,  1196.705 ,   521.3143,   199.0874],
       [80229.    ,  1134.806 ,   456.8394,   225.2395]])

In [41]:
y_test

array(['Ürgüp Sivrisi', 'Çerçevelik', 'Çerçevelik', 'Çerçevelik',
       'Ürgüp Sivrisi', 'Çerçevelik', 'Çerçevelik', 'Ürgüp Sivrisi',
       'Ürgüp Sivrisi', 'Çerçevelik', 'Çerçevelik', 'Ürgüp Sivrisi',
       'Çerçevelik', 'Ürgüp Sivrisi', 'Ürgüp Sivrisi', 'Çerçevelik',
       'Ürgüp Sivrisi', 'Çerçevelik', 'Çerçevelik', 'Çerçevelik',
       'Ürgüp Sivrisi', 'Çerçevelik', 'Ürgüp Sivrisi', 'Ürgüp Sivrisi',
       'Çerçevelik', 'Ürgüp Sivrisi', 'Çerçevelik', 'Çerçevelik',
       'Çerçevelik', 'Ürgüp Sivrisi', 'Çerçevelik', 'Ürgüp Sivrisi',
       'Çerçevelik', 'Ürgüp Sivrisi', 'Çerçevelik', 'Ürgüp Sivrisi',
       'Çerçevelik', 'Ürgüp Sivrisi', 'Çerçevelik', 'Çerçevelik',
       'Çerçevelik', 'Çerçevelik', 'Çerçevelik', 'Ürgüp Sivrisi',
       'Ürgüp Sivrisi', 'Ürgüp Sivrisi', 'Ürgüp Sivrisi', 'Çerçevelik',
       'Ürgüp Sivrisi', 'Çerçevelik', 'Çerçevelik', 'Çerçevelik',
       'Çerçevelik', 'Çerçevelik', 'Çerçevelik', 'Ürgüp Sivrisi',
       'Çerçevelik', 'Ürgüp Sivrisi', 'Çerçevelik

In [43]:
from sklearn.preprocessing import LabelEncoder
le_y = LabelEncoder()
Y=le_y.fit_transform(y)
Y

array([0, 0, 0, ..., 1, 1, 1])

In [44]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
model = knn.fit(x_train,y_train)

In [45]:
from sklearn.model_selection import cross_val_score

In [54]:
score_train=cross_val_score(model, x_train,y_train,cv=5)
score_train

array([0.69  , 0.72  , 0.7025, 0.7175, 0.695 ])

In [55]:
print(np.mean(score_train))

0.705


In [56]:
prediction=cross_val_score(model,x_test,y_test)
prediction

array([0.6 , 0.62, 0.62, 0.52, 0.56])

In [57]:
score_test=cross_val_score(model, x_test,y_test,cv=5)
score_test

array([0.6 , 0.62, 0.62, 0.52, 0.56])

In [58]:
print(np.mean(score_test))

0.584
